version: '3.4'

services:
  ##### CMS
  mcuwidgets:
    extends:
      file: CMS/docker/docker-services.yml
      service: mcuwidgets

  mcuwidgetsDB:
    extends:
      file: CMS/docker/docker-services.yml
      service: mcuwidgetsDB
      
  ##### RECOMMENDATIONS
  mcu-widgets-recommendations-api:
    extends:
      file: recommendations-api/docker/docker-services.yml
      service: mcu-widgets-recommendations-api

  mcu-widgets-recommendations-db:
    extends:
      file: recommendations-api/docker/docker-services.yml
      service: mcu-widgets-recommendations-db

  ##### RabbitMQ
  messageQueue:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PWD}


volumes:
  mcuwidgets-data:
  mcu-widgets-recommendations-db:
  mcuwidgets-cms-data:


networks:
  default:
    name: nginxproxymanager_default
    external: true
