version: '3.4'

services:
  mcuwidgets:
    extends:
      file: CMS/docker/docker-services.yml
      service: mcuwidgets

  mcuwidgetsDB:
    extends:
      file: CMS/docker/docker-services.yml
      service: mcuwidgetsDB
      
  mcu-widgets-recommendations-api:
    extends:
      file: recommendations-api/docker/docker-services.yml
      service: mcu-widgets-recommendations-api

  mcu-widgets-recommendations-db:
    extends:
      file: recommendations-api/docker/docker-services.yml
      service: mcu-widgets-recommendations-db

volumes:
  mcuwidgets-data:
  mcu-widgets-recommendations-db:


networks:
  default:
    name: nginxproxymanager_default
    external: false
