/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import entityNotes from "strapi-plugin-notes/strapi-admin";
// import restCache from "strapi-plugin-rest-cache/strapi-admin";
import todo from "strapi-plugin-todo/strapi-admin";
import dataResolvingTask from "../../src/plugins/data-resolving-task/strapi-admin";
import strapiPluginFcm from "../../src/plugins/strapi-plugin-fcm/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    i18n: i18N,
    "users-permissions": usersPermissions,
    "entity-notes": entityNotes,
    // "rest-cache": restCache,
    todo: todo,
    "data-resolving-task": dataResolvingTask,
    "strapi-plugin-fcm": strapiPluginFcm,
  },
});
