services:
  mcu-widgets-recommendations-api:
    pull_policy: build
    build:
      context: ../MCUWidgetsRecommendationsApi/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      RECOMMENDATIONS_DATABASE_PASSWORD: ${RECOMMENDATIONS_DATABASE_PASSWORD}
      RECOMMENDATIONS_DATABASE_NAME: ${RECOMMENDATIONS_DATABASE_NAME}
    ports:
      - "8000:80"
    depends_on:
      mcu-widgets-recommendations-db:
        condition: service_healthy

  mcu-widgets-recommendations-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${RECOMMENDATIONS_DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${RECOMMENDATIONS_DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${RECOMMENDATIONS_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${RECOMMENDATIONS_DATABASE_NAME}
    volumes:
      - mcu-widgets-recommendations-db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=${RECOMMENDATIONS_DATABASE_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
