services:
  mcu-widgets-recommendations-api:
    pull_policy: build
    build:
      context: ../MCUWidgetsRecommendationsApi/
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    depends_on:
      mcu-widgets-recommendations-db:
        condition: service_healthy

  mcu-widgets-recommendations-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: MCUWidgetsRecommendationsDB
    volumes:
      - mcu-widgets-recommendations-db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=${DATABASE_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
